import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import ts from 'typescript';

import { discoverControls, type DiscoveredControl } from './discover';
import { DISQUALIFIED, serializeType } from './serialize';

import type {
  ControlTypes,
  ParamBinding,
  TypeDeclaration,
  TypeMatrix,
} from '../../apps/docs/src/app/utils/playground/type-model';

const CONTROLS_ROOT = resolve(import.meta.dirname, '../../packages/controls');
const SRC_DIR = join(CONTROLS_ROOT, 'src');
// Outside `src`, so a killed run cannot leave a stray file the package build picks up.
const PROBE_FILE = join(CONTROLS_ROOT, '__type-probe.generated.ts');
const PROBE_DIR = dirname(PROBE_FILE);
const TSCONFIG = join(CONTROLS_ROOT, 'tsconfig.typedoc.json');
const SIGNAL_WRAPPERS = ['InputSignal', 'InputSignalWithTransform', 'ModelSignal'];
const MAX_COMBOS = 8;

interface Probe {
  control: string;
  key: string;
  variable: string;
}

/** `boolean`-constrained parameters are enumerated; everything else gets a placeholder. */
function domainOf(constraint: string | null): boolean[] | null {
  return constraint === 'boolean' ? [false, true] : null;
}

function combinations(domains: boolean[][]): boolean[][] {
  return domains.reduce<boolean[][]>(
    (acc, domain) => acc.flatMap(row => domain.map(value => [...row, value])),
    [[]]
  );
}

function buildProbeSource(controls: DiscoveredControl[]): { source: string; probes: Probe[] } {
  const imports: string[] = ['/* Generated by tools/type-matrix. Do not edit. */'];
  const placeholders = new Set<string>();
  const declarations: string[] = [];
  const probes: Probe[] = [];

  controls.forEach((control, index) => {
    const importPath = `./${relative(PROBE_DIR, control.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`;
    imports.push(`import type { ${control.name} as C${index} } from '${importPath}';`);

    const finite = control.typeParams.filter(param => domainOf(param.constraint));
    let rows = combinations(finite.map(param => domainOf(param.constraint)!));
    if (rows.length > MAX_COMBOS) {
      // Too many to enumerate — keep the all-defaults row so the control still has
      // inputs in the playground instead of silently rendering none.
      console.warn(
        `[type-matrix] ${control.name}: ${rows.length} combinations exceed ${MAX_COMBOS}, ` +
          'keeping the all-defaults combination only'
      );
      rows = [finite.map(() => false)];
    }

    rows.forEach((row, rowIndex) => {
      const args = control.typeParams.map(param => {
        const position = finite.findIndex(p => p.name === param.name);
        if (position === -1) {
          const placeholder = `__P_${param.name}`;
          placeholders.add(placeholder);
          return placeholder;
        }
        return String(row[position]);
      });

      const variable = `probe_${index}_${rowIndex}`;
      const generics = args.length ? `<${args.join(', ')}>` : '';
      declarations.push(`export declare const ${variable}: C${index}${generics};`);
      probes.push({ control: control.name, key: row.join('|'), variable });
    });
  });

  const placeholderDecls = [...placeholders].map(
    name => `interface ${name} { readonly __jigParam: '${name}'; }`
  );

  return { source: [...imports, ...placeholderDecls, ...declarations, ''].join('\n'), probes };
}

function createProgram(): ts.Program {
  const config = ts.getParsedCommandLineOfConfigFile(
    TSCONFIG,
    { noEmit: true },
    {
      ...ts.sys,
      onUnRecoverableConfigFileDiagnostic: diagnostic => {
        throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'));
      },
    }
  );
  if (!config) throw new Error(`Could not read ${TSCONFIG}`);
  return ts.createProgram({ rootNames: [PROBE_FILE], options: config.options });
}

function isPublicInput(symbol: ts.Symbol): boolean {
  const declaration = symbol.declarations?.[0];
  if (!declaration) return false;
  const modifiers = ts.getCombinedModifierFlags(declaration as ts.Declaration);
  return !(modifiers & (ts.ModifierFlags.Private | ts.ModifierFlags.Protected));
}

/** Unwraps `InputSignal<T, …>` / `ModelSignal<T>` to `T`. */
function unwrapSignal(type: ts.Type, checker: ts.TypeChecker): ts.Type | null {
  const name = type.getSymbol()?.getName();
  if (!name || !SIGNAL_WRAPPERS.includes(name)) return null;
  return checker.getTypeArguments(type as ts.TypeReference)[0] ?? null;
}

/** Reads the `@alias` JSDoc tag, which renames the input in the API docs. */
function aliasOf(symbol: ts.Symbol): string | null {
  const tag = symbol.getJsDocTags().find(t => t.name === 'alias');
  return (
    tag?.text
      ?.map(part => part.text)
      .join('')
      .trim() || null
  );
}

/** The class declaring the input, which may be a base class. */
function ownerOf(symbol: ts.Symbol): string | null {
  const parent = symbol.declarations?.[0]?.parent;
  return parent && ts.isClassDeclaration(parent) ? (parent.name?.text ?? null) : null;
}

function inputTypeOf(symbol: ts.Symbol, checker: ts.TypeChecker): ts.Type | null {
  const declaration = symbol.declarations?.[0];
  if (!declaration || !isPublicInput(symbol)) return null;
  return unwrapSignal(checker.getTypeOfSymbolAtLocation(symbol, declaration), checker);
}

/** The class as declared, with its type parameters still unsubstituted. */
function declaredClassType(
  control: DiscoveredControl,
  program: ts.Program,
  checker: ts.TypeChecker
): ts.Type | null {
  const source = program.getSourceFile(control.file);
  const declaration = source?.statements.find(
    (statement): statement is ts.ClassDeclaration =>
      ts.isClassDeclaration(statement) && statement.name?.text === control.name
  );
  const symbol = declaration?.name && checker.getSymbolAtLocation(declaration.name);
  return symbol ? checker.getDeclaredTypeOfSymbol(symbol) : null;
}

function paramBindings(
  control: DiscoveredControl,
  classType: ts.Type,
  checker: ts.TypeChecker
): ParamBinding[] {
  const properties = checker.getPropertiesOfType(classType);

  return control.typeParams
    .filter(param => domainOf(param.constraint))
    .map(param => {
      const match = properties.find(symbol => {
        const type = inputTypeOf(symbol, checker);
        if (!type) return false;
        const members = type.isUnion() ? type.types : [type];
        return members.some(t => t.isTypeParameter() && t.getSymbol()?.getName() === param.name);
      });
      return { name: param.name, input: match?.getName() ?? null, default: false };
    });
}

export async function generateTypeMatrix(): Promise<TypeMatrix> {
  const controls = discoverControls(SRC_DIR);
  const { source, probes } = buildProbeSource(controls);
  await writeFile(PROBE_FILE, source, 'utf-8');

  try {
    const program = createProgram();
    const checker = program.getTypeChecker();
    const probeSource = program.getSourceFile(PROBE_FILE);
    if (!probeSource) throw new Error('Probe file missing from the program');

    const declarations = new Map<string, ts.VariableDeclaration>();
    for (const statement of probeSource.statements) {
      if (!ts.isVariableStatement(statement)) continue;
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name)) declarations.set(declaration.name.text, declaration);
      }
    }

    const matrix: TypeMatrix = {};

    for (const probe of probes) {
      const declaration = declarations.get(probe.variable);
      if (!declaration) continue;
      const classType = checker.getTypeAtLocation(declaration.name);
      const control = controls.find(c => c.name === probe.control)!;

      const declared = declaredClassType(control, program, checker);
      const entry: ControlTypes = (matrix[probe.control] ??= {
        params: declared ? paramBindings(control, declared, checker) : [],
        owners: {},
        combos: {},
      });

      const boundInputs = new Set(entry.params.map(param => param.input));

      const inputs: Record<string, TypeDeclaration> = {};
      for (const symbol of checker.getPropertiesOfType(classType)) {
        const type = inputTypeOf(symbol, checker);
        if (!type) continue;
        const name = aliasOf(symbol) ?? symbol.getName();
        // The parameter is pinned to this combination, but the input still offers both values.
        if (boundInputs.has(symbol.getName())) {
          inputs[name] = { kind: 'primitive', type: 'boolean', optional: true };
        } else {
          try {
            inputs[name] = serializeType(type, checker);
          } catch (error) {
            if (error !== DISQUALIFIED) throw error;
            continue;
          }
        }
        const owner = ownerOf(symbol);
        if (owner) {
          entry.owners[name] = owner;
        }
      }
      entry.combos[probe.key] = inputs;
    }

    return matrix;
  } finally {
    await rm(PROBE_FILE, { force: true });
  }
}

export async function writeTypeMatrix(outFile: string): Promise<void> {
  const matrix = await generateTypeMatrix();
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, JSON.stringify(matrix), 'utf-8');
}
