packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  awesome-logging: false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false

catalog:
  '@angular/animations': 22.0.5
  '@angular/build': 22.0.5
  '@angular/cli': 22.0.5
  '@angular/common': 22.0.5
  '@angular/compiler': 22.0.5
  '@angular/compiler-cli': 22.0.5
  '@angular/core': 22.0.5
  '@angular/forms': 22.0.5
  '@angular/platform-browser': 22.0.5
  '@angular/platform-server': 22.0.5
  '@angular/router': 22.0.5
  '@angular/ssr': 22.0.5
  typescript: ~6.0.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - awesome-logging
  - less
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - esbuild
