packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  awesome-logging: false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false

catalog:
  '@angular/animations': 21.2.10
  '@angular/build': 21.2.8
  '@angular/cli': 21.2.8
  '@angular/common': 21.2.10
  '@angular/compiler': 21.2.10
  '@angular/compiler-cli': 21.2.10
  '@angular/core': 21.2.10
  '@angular/forms': 21.2.10
  '@angular/platform-browser': 21.2.10
  '@angular/platform-server': 21.2.10
  '@angular/router': 21.2.10
  '@angular/ssr': 21.2.8
  typescript: ~5.9.3

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - awesome-logging
  - less
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - esbuild
