/**
 * Generates the SEO artefacts that need to know every docs route:
 *
 *   src/app/docs/_generated/seo.ts   per-route title + description, imported by `Seo`
 *   public/sitemap.xml               every canonical URL
 *   public/llms.txt                  the docs index, for AI agents
 *
 * Routes, titles and tabs come from `docs-pages.ts` — the same reader the search
 * index and API links use, so a page cannot be routed two different ways.
 * Descriptions come from the first prose paragraph of the page's default
 * markdown tab, so they stay in sync with the content without a second place to
 * maintain.
 *
 * Runs from `prepare-docs`, before the build. Outputs are gitignored.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { DOCS_DIR, readPageMeta, readTabSlugs, tabRoutes, walk } from './docs-pages';

const GENERATED_DIR = join(DOCS_DIR, '_generated');
const PUBLIC_DIR = join(import.meta.dirname, '../public');

export const SITE_URL = 'https://ngneers.dev';

/** Longest a meta description should get before search engines truncate it. */
const DESCRIPTION_LENGTH = 155;

type Page = {
  /** Route path without a leading slash, e.g. `components/select`. */
  route: string;
  title: string;
  /** Tab title of the containing area, e.g. `Components`. */
  area: string;
  description: string;
};

/**
 * First real paragraph of a markdown file, flattened to a single sentence-ish
 * line. Directives, fences, headings, tables and blockquotes are skipped —
 * none of them read as a description.
 */
function extractDescription(md: string): string {
  const body = md
    .replace(/^```[\s\S]*?^```/gm, '')
    .replace(/{{\s*[a-zA-Z0-9_-]+\s*:[^}]+}}/g, '')
    .split('\n');

  const lines: string[] = [];
  for (const line of body) {
    const trimmed = line.trim();
    if (!trimmed) {
      if (lines.length) break; // paragraph ended
      continue;
    }
    if (/^[#>|]/.test(trimmed) || /^[-*]\s/.test(trimmed) || trimmed.startsWith('|')) {
      if (lines.length) break;
      continue;
    }
    lines.push(trimmed);
  }

  const prose = lines
    .join(' ')
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[`*_]/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (prose.length <= DESCRIPTION_LENGTH) {
    return prose;
  }
  // Cut on a word boundary rather than mid-word.
  const cut = prose.slice(0, DESCRIPTION_LENGTH);
  return `${cut.slice(0, cut.lastIndexOf(' '))}…`;
}

async function collectPages(): Promise<Page[]> {
  const pageFiles = (await walk(DOCS_DIR, p => p.endsWith('page.ts'))).sort();
  const tabSlugs = await readTabSlugs();
  const pages: Page[] = [];

  for (const file of pageFiles) {
    const { pageTitle, tabs } = await readPageMeta(file);
    // Only the default tab has a canonical URL of its own. A page that renders
    // itself (the changelog) has no markdown, and so no prose to describe it.
    const tab = tabs.find(t => t.isDefault);
    if (!tab) {
      continue;
    }
    const { pageRoute } = tabRoutes(pageTitle, tab, tabSlugs);
    const md = await readFile(join(DOCS_DIR, tab.mdFile), 'utf8');
    pages.push({
      route: pageRoute,
      title: pageTitle,
      // `components/select` → `Components`, the llms.txt section it belongs to.
      area: pageRoute.split('/')[0]?.replace(/^./, c => c.toUpperCase()) ?? '',
      description: extractDescription(md),
    });
  }

  return pages;
}

function renderSeoModule(pages: Page[]): string {
  const entries = pages
    .map(page => `  '${page.route}': ${JSON.stringify(page.description)},`)
    .join('\n');

  return `// GENERATED by tools/seo-gen.ts — do not edit.
// Per-route meta descriptions, taken from each page's opening paragraph.

export const PAGE_DESCRIPTIONS: Readonly<Record<string, string>> = {
${entries}
};
`;
}

function renderSitemap(pages: Page[]): string {
  const urls = ['', ...pages.map(page => page.route)]
    .map(
      route =>
        `  <url>\n    <loc>${SITE_URL}/${route}</loc>\n` +
        `    <changefreq>weekly</changefreq>\n` +
        `    <priority>${route === '' ? '1.0' : route.split('/').length > 1 ? '0.8' : '0.6'}</priority>\n  </url>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function renderLlmsTxt(pages: Page[]): string {
  const byArea = new Map<string, Page[]>();
  for (const page of pages) {
    byArea.set(page.area, [...(byArea.get(page.area) ?? []), page]);
  }

  const sections = [...byArea.entries()]
    .map(([area, areaPages]) => {
      const lines = areaPages
        .map(page => `- [${page.title}](${SITE_URL}/${page.route}): ${page.description}`)
        .join('\n');
      return `## ${area}\n\n${lines}`;
    })
    .join('\n\n');

  return `# @ngneers/controls

> A signal-based component library for Angular 22+. Controls ship no CSS of their
> own: behaviour, accessibility and named style scopes live in the control, while
> all styling comes from a swappable theme that the engine injects at runtime.

Angular 22+, zoneless, standalone, no NgModules, no ControlValueAccessor.
Packages: \`@ngneers/controls\` (controls), \`@ngneers/controls-themes\` (theming),
\`@ngneers/controls-playwright\` (test harnesses), \`@ngneers/controls-mcp\` (MCP server).

Every page below is also available as raw markdown by prefixing the path with
\`/md/\` — for example ${SITE_URL}/md/components/select/index.md.

${sections}
`;
}

async function main() {
  const pages = await collectPages();

  await mkdir(GENERATED_DIR, { recursive: true });
  await writeFile(join(GENERATED_DIR, 'seo.ts'), renderSeoModule(pages));
  await writeFile(join(PUBLIC_DIR, 'sitemap.xml'), renderSitemap(pages));
  await writeFile(join(PUBLIC_DIR, 'llms.txt'), renderLlmsTxt(pages));

  console.log(`[seo] ${pages.length} routes → seo.ts, sitemap.xml, llms.txt`);
}

await main();
