export const IMPORTS = {
  accordion: () => import('@awdlab/jig/accordion').then(m => m.NgnAccordion),
  accordionPanel: () => import('@awdlab/jig/accordion').then(m => m.NgnAccordionPanel),
  actionButton: () => import('@awdlab/jig/button').then(m => m.NgnActionButton),
  avatar: () => import('@awdlab/jig/avatar').then(m => m.NgnAvatar),
  avatarGroup: () => import('@awdlab/jig/avatar').then(m => m.NgnAvatarGroup),
  badge: () => import('@awdlab/jig/badge').then(m => m.NgnBadge),
  breadcrumb: () => import('@awdlab/jig/breadcrumb').then(m => m.NgnBreadcrumb),
  button: () => import('@awdlab/jig/button').then(m => m.NgnButton),
  buttonGroup: () => import('@awdlab/jig/button-group').then(m => m.NgnButtonGroup),
  calendar: () => import('@awdlab/jig/calendar').then(m => m.NgnCalendar),
  checkbox: () => import('@awdlab/jig/checkbox').then(m => m.NgnCheckbox),
  chip: () => import('@awdlab/jig/chip').then(m => m.NgnChip),
  'color-picker': () => import('@awdlab/jig/color-picker').then(m => m.NgnColorPicker),
  command: () => import('@awdlab/jig/command').then(m => m.NgnCommand),
  defer: () => import('@awdlab/jig/defer').then(m => m.NgnDefer),
  dialog: () => import('@awdlab/jig/dialog').then(m => m.NgnDialog),
  drawer: () => import('@awdlab/jig/drawer').then(m => m.NgnDrawer),
  menu: () => import('@awdlab/jig/menu').then(m => m.NgnMenu),
  editInplace: () => import('@awdlab/jig/edit-inplace').then(m => m.NgnEditInplace),
  errors: () => import('@awdlab/jig/errors').then(m => m.NgnErrors),
  filter: () => import('@awdlab/jig/filter').then(m => m.NgnFilter),
  forms: () => import('@angular/forms').then(m => m.FormsModule),
  reactiveForms: () => import('@angular/forms').then(m => m.ReactiveFormsModule),
  hint: () => import('@awdlab/jig/hint').then(m => m.NgnHint),
  icon: () => import('@awdlab/jig/icon').then(m => m.NgnIcon),
  inplace: () => import('@awdlab/jig/inplace').then(m => m.NgnInplace),
  input: () => import('@awdlab/jig/input').then(m => m.NgnInput),
  inputField: () => import('@awdlab/jig/input-field').then(m => m.NgnInputField),
  maskInput: () => import('@awdlab/jig/mask-input').then(m => m.NgnMaskInput),
  itemView: () => import('@awdlab/jig/item-view').then(m => m.NgnItemView),
  kbd: () => import('@awdlab/jig/kbd').then(m => m.NgnKbd),
  keyboardShortcut: () => import('@awdlab/jig/kbd').then(m => m.NgnKeyboardShortcut),
  listBox: () => import('@awdlab/jig/list-box').then(m => m.NgnListBox),
  message: () => import('@awdlab/jig/message').then(m => m.NgnMessage),
  movable: () => import('@awdlab/jig/directives').then(m => m.NgnMovable),
  resizable: () => import('@awdlab/jig/directives').then(m => m.NgnResizable),
  numberInput: () => import('@awdlab/jig/number-input').then(m => m.NgnNumberInput),
  otp: () => import('@awdlab/jig/otp').then(m => m.NgnOtp),
  paginator: () => import('@awdlab/jig/paginator').then(m => m.NgnPaginator),
  popover: () => import('@awdlab/jig/popover').then(m => m.NgnPopover),
  progress: () => import('@awdlab/jig/progress').then(m => m.NgnProgress),
  radioGroup: () => import('@awdlab/jig/radio').then(m => m.NgnRadioGroup),
  radio: () => import('@awdlab/jig/radio').then(m => m.NgnRadio),
  rating: () => import('@awdlab/jig/rating').then(m => m.NgnRating),
  scrollShadow: () => import('@awdlab/jig/scroll-shadow').then(m => m.NgnScrollShadow),
  scroller: () => [
    import('@awdlab/jig/scroller').then(m => m.NgnScroller),
    import('@awdlab/jig/scroller').then(m => m.NgnScrollerItem),
  ],
  select: () => import('@awdlab/jig/select').then(m => m.NgnSelect),
  selectButton: () => import('@awdlab/jig/select-button').then(m => m.NgnSelectButton),
  slider: () => import('@awdlab/jig/slider').then(m => m.NgnSlider),
  snackbar: () => import('@awdlab/jig/snackbar').then(m => m.NgnSnackbar),
  spinButtons: () => import('@awdlab/jig/spin-buttons').then(m => m.NgnSpinButtons),
  spinner: () => import('@awdlab/jig/spinner').then(m => m.NgnSpinner),
  state: () => import('@awdlab/jig/state').then(m => m.NgnState),
  stepper: () => import('@awdlab/jig/stepper').then(m => m.NgnStepper),
  step: () => import('@awdlab/jig/stepper').then(m => m.NgnStep),
  splitter: () => import('@awdlab/jig/splitter').then(m => m.NgnSplitter),
  splitterPanel: () => import('@awdlab/jig/splitter').then(m => m.NgnSplitterPanel),
  switch: () => import('@awdlab/jig/switch').then(m => m.NgnSwitch),
  tabs: () => import('@awdlab/jig/tabs').then(m => m.NgnTabs),
  tab: () => import('@awdlab/jig/tabs').then(m => m.NgnTab),
  table: () => import('@awdlab/jig/table').then(m => m.NgnTable),
  tableModule: () => import('@awdlab/jig/table').then(m => m.NgnTableModule),
  tableSelectionColumn: () => import('@awdlab/jig/table').then(m => m.NgnTableSelectionColumn),
  tableSortableColumn: () => import('@awdlab/jig/table').then(m => m.NgnTableSortableColumn),
  tableStickyColumn: () => import('@awdlab/jig/table').then(m => m.NgnTableStickyColumn),
  ngnTemplate: () => import('@awdlab/jig/api/ng').then(m => m.NgnTemplate),
  tag: () => import('@awdlab/jig/tag').then(m => m.NgnTag),
  toast: () => import('@awdlab/jig/toast').then(m => m.NgnToast),
  toggleButton: () => import('@awdlab/jig/toggle-button').then(m => m.NgnToggleButton),
  tooltip: () => import('@awdlab/jig/tooltip').then(m => m.NgnTooltip),
  tree: () => import('@awdlab/jig/tree').then(m => m.NgnTree),
  upload: () => import('@awdlab/jig/upload').then(m => m.NgnUpload),
  dummy_component: () => import('./helper-components/dummy').then(m => m.DummyComponent),
  testAsyncValidator: () =>
    import('./helper-components/async-validator').then(m => m.TestAsyncValidator),
  toastTrigger: () => import('./helper-components/toast-trigger').then(m => m.ToastTrigger),
};
