export const IMPORTS = {
  accordion: () => import('@awdlab/jig/accordion').then(m => m.JigAccordion),
  accordionPanel: () => import('@awdlab/jig/accordion').then(m => m.JigAccordionPanel),
  actionButton: () => import('@awdlab/jig/button').then(m => m.JigActionButton),
  avatar: () => import('@awdlab/jig/avatar').then(m => m.JigAvatar),
  avatarGroup: () => import('@awdlab/jig/avatar').then(m => m.JigAvatarGroup),
  badge: () => import('@awdlab/jig/badge').then(m => m.JigBadge),
  breadcrumb: () => import('@awdlab/jig/breadcrumb').then(m => m.JigBreadcrumb),
  button: () => import('@awdlab/jig/button').then(m => m.JigButton),
  buttonGroup: () => import('@awdlab/jig/button-group').then(m => m.JigButtonGroup),
  calendar: () => import('@awdlab/jig/calendar').then(m => m.JigCalendar),
  checkbox: () => import('@awdlab/jig/checkbox').then(m => m.JigCheckbox),
  chip: () => import('@awdlab/jig/chip').then(m => m.JigChip),
  'color-picker': () => import('@awdlab/jig/color-picker').then(m => m.JigColorPicker),
  command: () => import('@awdlab/jig/command').then(m => m.JigCommand),
  defer: () => import('@awdlab/jig/defer').then(m => m.JigDefer),
  dialog: () => import('@awdlab/jig/dialog').then(m => m.JigDialog),
  drawer: () => import('@awdlab/jig/drawer').then(m => m.JigDrawer),
  dropdownList: () => import('@awdlab/jig/dropdown-list').then(m => m.JigDropdownList),
  menu: () => import('@awdlab/jig/menu').then(m => m.JigMenu),
  editInplace: () => import('@awdlab/jig/edit-inplace').then(m => m.JigEditInplace),
  errors: () => import('@awdlab/jig/errors').then(m => m.JigErrors),
  filter: () => import('@awdlab/jig/filter').then(m => m.JigFilter),
  forms: () => import('@angular/forms').then(m => m.FormsModule),
  reactiveForms: () => import('@angular/forms').then(m => m.ReactiveFormsModule),
  hint: () => import('@awdlab/jig/hint').then(m => m.JigHint),
  icon: () => import('@awdlab/jig/icon').then(m => m.JigIcon),
  inplace: () => import('@awdlab/jig/inplace').then(m => m.JigInplace),
  input: () => import('@awdlab/jig/input').then(m => m.JigInput),
  inputField: () => import('@awdlab/jig/input-field').then(m => m.JigInputField),
  maskInput: () => import('@awdlab/jig/mask-input').then(m => m.JigMaskInput),
  itemView: () => import('@awdlab/jig/item-view').then(m => m.JigItemView),
  kbd: () => import('@awdlab/jig/kbd').then(m => m.JigKbd),
  keyboardShortcut: () => import('@awdlab/jig/kbd').then(m => m.JigKeyboardShortcut),
  listBox: () => import('@awdlab/jig/list-box').then(m => m.JigListBox),
  message: () => import('@awdlab/jig/message').then(m => m.JigMessage),
  movable: () => import('@awdlab/jig/directives').then(m => m.JigMovable),
  resizable: () => import('@awdlab/jig/directives').then(m => m.JigResizable),
  numberInput: () => import('@awdlab/jig/number-input').then(m => m.JigNumberInput),
  otp: () => import('@awdlab/jig/otp').then(m => m.JigOtp),
  paginator: () => import('@awdlab/jig/paginator').then(m => m.JigPaginator),
  popover: () => import('@awdlab/jig/popover').then(m => m.JigPopover),
  progress: () => import('@awdlab/jig/progress').then(m => m.JigProgress),
  radioGroup: () => import('@awdlab/jig/radio').then(m => m.JigRadioGroup),
  radio: () => import('@awdlab/jig/radio').then(m => m.JigRadio),
  rating: () => import('@awdlab/jig/rating').then(m => m.JigRating),
  scrollShadow: () => import('@awdlab/jig/scroll-shadow').then(m => m.JigScrollShadow),
  scroller: () => [
    import('@awdlab/jig/scroller').then(m => m.JigScroller),
    import('@awdlab/jig/scroller').then(m => m.JigScrollerItem),
  ],
  select: () => import('@awdlab/jig/select').then(m => m.JigSelect),
  selectButton: () => import('@awdlab/jig/select-button').then(m => m.JigSelectButton),
  slider: () => import('@awdlab/jig/slider').then(m => m.JigSlider),
  snackbar: () => import('@awdlab/jig/snackbar').then(m => m.JigSnackbar),
  spinButtons: () => import('@awdlab/jig/spin-buttons').then(m => m.JigSpinButtons),
  spinner: () => import('@awdlab/jig/spinner').then(m => m.JigSpinner),
  state: () => import('@awdlab/jig/state').then(m => m.JigState),
  stepper: () => import('@awdlab/jig/stepper').then(m => m.JigStepper),
  step: () => import('@awdlab/jig/stepper').then(m => m.JigStep),
  splitter: () => import('@awdlab/jig/splitter').then(m => m.JigSplitter),
  splitterPanel: () => import('@awdlab/jig/splitter').then(m => m.JigSplitterPanel),
  switch: () => import('@awdlab/jig/switch').then(m => m.JigSwitch),
  tabs: () => import('@awdlab/jig/tabs').then(m => m.JigTabs),
  tab: () => import('@awdlab/jig/tabs').then(m => m.JigTab),
  table: () => import('@awdlab/jig/table').then(m => m.JigTable),
  tableModule: () => import('@awdlab/jig/table').then(m => m.JigTableModule),
  tableSelectionColumn: () => import('@awdlab/jig/table').then(m => m.JigTableSelectionColumn),
  tableSortableColumn: () => import('@awdlab/jig/table').then(m => m.JigTableSortableColumn),
  tableStickyColumn: () => import('@awdlab/jig/table').then(m => m.JigTableStickyColumn),
  jigTemplate: () => import('@awdlab/jig/api/ng').then(m => m.JigTemplate),
  tag: () => import('@awdlab/jig/tag').then(m => m.JigTag),
  tagInput: () => import('@awdlab/jig/tag-input').then(m => m.JigTagInput),
  toast: () => import('@awdlab/jig/toast').then(m => m.JigToast),
  toggleButton: () => import('@awdlab/jig/toggle-button').then(m => m.JigToggleButton),
  tooltip: () => import('@awdlab/jig/tooltip').then(m => m.JigTooltip),
  tree: () => import('@awdlab/jig/tree').then(m => m.JigTree),
  upload: () => import('@awdlab/jig/upload').then(m => m.JigUpload),
  dummy_component: () => import('./helper-components/dummy').then(m => m.DummyComponent),
  testAsyncValidator: () =>
    import('./helper-components/async-validator').then(m => m.TestAsyncValidator),
  toastTrigger: () => import('./helper-components/toast-trigger').then(m => m.ToastTrigger),
  tagForm: () => import('./helper-components/tag-form').then(m => m.TagForm),
};
