export const IMPORTS = {
  accordion: () => import('@awdlab/jig/accordion').then(m => m.AwdAccordion),
  accordionPanel: () => import('@awdlab/jig/accordion').then(m => m.AwdAccordionPanel),
  actionButton: () => import('@awdlab/jig/button').then(m => m.AwdActionButton),
  avatar: () => import('@awdlab/jig/avatar').then(m => m.AwdAvatar),
  avatarGroup: () => import('@awdlab/jig/avatar').then(m => m.AwdAvatarGroup),
  badge: () => import('@awdlab/jig/badge').then(m => m.AwdBadge),
  breadcrumb: () => import('@awdlab/jig/breadcrumb').then(m => m.AwdBreadcrumb),
  button: () => import('@awdlab/jig/button').then(m => m.AwdButton),
  buttonGroup: () => import('@awdlab/jig/button-group').then(m => m.AwdButtonGroup),
  calendar: () => import('@awdlab/jig/calendar').then(m => m.AwdCalendar),
  checkbox: () => import('@awdlab/jig/checkbox').then(m => m.AwdCheckbox),
  chip: () => import('@awdlab/jig/chip').then(m => m.AwdChip),
  'color-picker': () => import('@awdlab/jig/color-picker').then(m => m.AwdColorPicker),
  command: () => import('@awdlab/jig/command').then(m => m.AwdCommand),
  defer: () => import('@awdlab/jig/defer').then(m => m.AwdDefer),
  dialog: () => import('@awdlab/jig/dialog').then(m => m.AwdDialog),
  drawer: () => import('@awdlab/jig/drawer').then(m => m.AwdDrawer),
  menu: () => import('@awdlab/jig/menu').then(m => m.AwdMenu),
  editInplace: () => import('@awdlab/jig/edit-inplace').then(m => m.AwdEditInplace),
  errors: () => import('@awdlab/jig/errors').then(m => m.AwdErrors),
  filter: () => import('@awdlab/jig/filter').then(m => m.AwdFilter),
  forms: () => import('@angular/forms').then(m => m.FormsModule),
  reactiveForms: () => import('@angular/forms').then(m => m.ReactiveFormsModule),
  hint: () => import('@awdlab/jig/hint').then(m => m.AwdHint),
  icon: () => import('@awdlab/jig/icon').then(m => m.AwdIcon),
  inplace: () => import('@awdlab/jig/inplace').then(m => m.AwdInplace),
  input: () => import('@awdlab/jig/input').then(m => m.AwdInput),
  inputField: () => import('@awdlab/jig/input-field').then(m => m.AwdInputField),
  maskInput: () => import('@awdlab/jig/mask-input').then(m => m.AwdMaskInput),
  itemView: () => import('@awdlab/jig/item-view').then(m => m.JigItemView),
  kbd: () => import('@awdlab/jig/kbd').then(m => m.AwdKbd),
  keyboardShortcut: () => import('@awdlab/jig/kbd').then(m => m.AwdKeyboardShortcut),
  listBox: () => import('@awdlab/jig/list-box').then(m => m.AwdListBox),
  message: () => import('@awdlab/jig/message').then(m => m.AwdMessage),
  movable: () => import('@awdlab/jig/directives').then(m => m.AwdMovable),
  resizable: () => import('@awdlab/jig/directives').then(m => m.AwdResizable),
  numberInput: () => import('@awdlab/jig/number-input').then(m => m.AwdNumberInput),
  otp: () => import('@awdlab/jig/otp').then(m => m.AwdOtp),
  paginator: () => import('@awdlab/jig/paginator').then(m => m.AwdPaginator),
  popover: () => import('@awdlab/jig/popover').then(m => m.AwdPopover),
  progress: () => import('@awdlab/jig/progress').then(m => m.AwdProgress),
  radioGroup: () => import('@awdlab/jig/radio').then(m => m.AwdRadioGroup),
  radio: () => import('@awdlab/jig/radio').then(m => m.AwdRadio),
  rating: () => import('@awdlab/jig/rating').then(m => m.AwdRating),
  scrollShadow: () => import('@awdlab/jig/scroll-shadow').then(m => m.AwdScrollShadow),
  scroller: () => [
    import('@awdlab/jig/scroller').then(m => m.AwdScroller),
    import('@awdlab/jig/scroller').then(m => m.AwdScrollerItem),
  ],
  select: () => import('@awdlab/jig/select').then(m => m.AwdSelect),
  selectButton: () => import('@awdlab/jig/select-button').then(m => m.AwdSelectButton),
  slider: () => import('@awdlab/jig/slider').then(m => m.AwdSlider),
  snackbar: () => import('@awdlab/jig/snackbar').then(m => m.AwdSnackbar),
  spinButtons: () => import('@awdlab/jig/spin-buttons').then(m => m.AwdSpinButtons),
  spinner: () => import('@awdlab/jig/spinner').then(m => m.AwdSpinner),
  state: () => import('@awdlab/jig/state').then(m => m.AwdState),
  stepper: () => import('@awdlab/jig/stepper').then(m => m.AwdStepper),
  step: () => import('@awdlab/jig/stepper').then(m => m.AwdStep),
  splitter: () => import('@awdlab/jig/splitter').then(m => m.AwdSplitter),
  splitterPanel: () => import('@awdlab/jig/splitter').then(m => m.AwdSplitterPanel),
  switch: () => import('@awdlab/jig/switch').then(m => m.AwdSwitch),
  tabs: () => import('@awdlab/jig/tabs').then(m => m.AwdTabs),
  tab: () => import('@awdlab/jig/tabs').then(m => m.AwdTab),
  table: () => import('@awdlab/jig/table').then(m => m.AwdTable),
  tableModule: () => import('@awdlab/jig/table').then(m => m.AwdTableModule),
  tableSelectionColumn: () => import('@awdlab/jig/table').then(m => m.AwdTableSelectionColumn),
  tableSortableColumn: () => import('@awdlab/jig/table').then(m => m.AwdTableSortableColumn),
  tableStickyColumn: () => import('@awdlab/jig/table').then(m => m.AwdTableStickyColumn),
  ngnTemplate: () => import('@awdlab/jig/api/ng').then(m => m.AwdTemplate),
  tag: () => import('@awdlab/jig/tag').then(m => m.AwdTag),
  toast: () => import('@awdlab/jig/toast').then(m => m.AwdToast),
  toggleButton: () => import('@awdlab/jig/toggle-button').then(m => m.AwdToggleButton),
  tooltip: () => import('@awdlab/jig/tooltip').then(m => m.AwdTooltip),
  tree: () => import('@awdlab/jig/tree').then(m => m.AwdTree),
  upload: () => import('@awdlab/jig/upload').then(m => m.AwdUpload),
  dummy_component: () => import('./helper-components/dummy').then(m => m.DummyComponent),
  testAsyncValidator: () =>
    import('./helper-components/async-validator').then(m => m.TestAsyncValidator),
  toastTrigger: () => import('./helper-components/toast-trigger').then(m => m.ToastTrigger),
};
