export type ThemeTemplate = {
  accordion: Awaited<typeof import('./accordion/index.js')>['accordionControlTemplate'];
  accordionPanel: Awaited<
    typeof import('./accordion-panel/index.js')
  >['accordionPanelControlTemplate'];
  movable: Awaited<typeof import('./api/index.js')>['movableDirectiveTemplate'];
  resizable: Awaited<typeof import('./api/index.js')>['resizableDirectiveTemplate'];
  scrollShadow: Awaited<typeof import('./api/index.js')>['scrollShadowDirectiveTemplate'];
  avatar: Awaited<typeof import('./avatar/index.js')>['avatarControlTemplate'];
  avatarGroup: Awaited<typeof import('./avatar/index.js')>['avatarGroupControlTemplate'];
  badge: Awaited<typeof import('./badge/index.js')>['badgeControlTemplate'];
  breadcrumb: Awaited<typeof import('./breadcrumb/index.js')>['breadcrumbControlTemplate'];
  button: Awaited<typeof import('./button/index.js')>['buttonControlTemplate'];
  buttonGroup: Awaited<typeof import('./button-group/index.js')>['buttonGroupControlTemplate'];
  calendar: Awaited<typeof import('./calendar/index.js')>['calendarControlTemplate'];
  checkbox: Awaited<typeof import('./checkbox/index.js')>['checkboxControlTemplate'];
  chip: Awaited<typeof import('./chip/index.js')>['chipControlTemplate'];
  'color-picker': Awaited<typeof import('./color-picker/index.js')>['colorPickerControlTemplate'];
  command: Awaited<typeof import('./command/index.js')>['commandControlTemplate'];
  dialog: Awaited<typeof import('./dialog/index.js')>['dialogControlTemplate'];
  drawer: Awaited<typeof import('./drawer/index.js')>['drawerControlTemplate'];
  dropdownList: Awaited<typeof import('./dropdown-list/index.js')>['dropdownListControlTemplate'];
  filter: Awaited<typeof import('./filter/index.js')>['filterControlTemplate'];
  editInplace: Awaited<typeof import('./edit-inplace/index.js')>['editInplaceControlTemplate'];
  global: Awaited<typeof import('./global/index.js')>['globalControlTemplate'];
  hint: Awaited<typeof import('./hint/index.js')>['hintControlTemplate'];
  icon: Awaited<typeof import('./icon/index.js')>['iconControlTemplate'];
  inplace: Awaited<typeof import('./inplace/index.js')>['inplaceControlTemplate'];
  input: Awaited<typeof import('./input/index.js')>['inputControlTemplate'];
  inputField: Awaited<typeof import('./input-field/index.js')>['inputFieldControlTemplate'];
  maskInput: Awaited<typeof import('./mask-input/index.js')>['maskInputControlTemplate'];
  itemView: Awaited<typeof import('./item-view/index.js')>['itemViewControlTemplate'];
  kbd: Awaited<typeof import('./kbd/index.js')>['kbdControlTemplate'];
  listBox: Awaited<typeof import('./list-box/index.js')>['listBoxControlTemplate'];
  menu: Awaited<typeof import('./menu/index.js')>['menuControlTemplate'];
  message: Awaited<typeof import('./message/index.js')>['messageControlTemplate'];
  meter: Awaited<typeof import('./meter/index.js')>['meterControlTemplate'];
  numberInput: Awaited<typeof import('./input/index.js')>['inputControlTemplate'];
  otp: Awaited<typeof import('./otp/index.js')>['otpControlTemplate'];
  paginator: Awaited<typeof import('./paginator/index.js')>['paginatorControlTemplate'];
  popover: Awaited<typeof import('./popover/index.js')>['popoverControlTemplate'];
  progress: Awaited<typeof import('./progress/index.js')>['progressControlTemplate'];
  radioGroup: Awaited<typeof import('./radio-group/index.js')>['radioGroupControlTemplate'];
  radio: Awaited<typeof import('./radio/index.js')>['radioControlTemplate'];
  rating: Awaited<typeof import('./rating/index.js')>['ratingControlTemplate'];
  scroller: Awaited<typeof import('./scroller/index.js')>['scrollerControlTemplate'];
  select: Awaited<typeof import('./select/index.js')>['selectControlTemplate'];
  selectButton: Awaited<typeof import('./select-button/index.js')>['selectButtonControlTemplate'];
  skeleton: Awaited<typeof import('./skeleton/index.js')>['skeletonControlTemplate'];
  slider: Awaited<typeof import('./slider/index.js')>['sliderControlTemplate'];
  snackbar: Awaited<typeof import('./snackbar/index.js')>['snackbarControlTemplate'];
  spinButtons: Awaited<typeof import('./spin-buttons/index.js')>['spinButtonsControlTemplate'];
  spinner: Awaited<typeof import('./spinner/index.js')>['spinnerControlTemplate'];
  splitter: Awaited<typeof import('./splitter/index.js')>['splitterControlTemplate'];
  state: Awaited<typeof import('./state/index.js')>['stateControlTemplate'];
  stepper: Awaited<typeof import('./stepper/index.js')>['stepperControlTemplate'];
  switch: Awaited<typeof import('./switch/index.js')>['switchControlTemplate'];
  tabs: Awaited<typeof import('./tabs/index.js')>['tabsControlTemplate'];
  table: Awaited<typeof import('./table/index.js')>['tableControlTemplate'];
  tag: Awaited<typeof import('./tag/index.js')>['tagControlTemplate'];
  tagInput: Awaited<typeof import('./tag-input/index.js')>['tagInputControlTemplate'];
  toast: Awaited<typeof import('./toast/index.js')>['toastControlTemplate'];
  toggleButton: Awaited<typeof import('./toggle-button/index.js')>['toggleButtonControlTemplate'];
  toolbar: Awaited<typeof import('./toolbar/index.js')>['toolbarControlTemplate'];
  toolbarRegion: Awaited<
    typeof import('./toolbar-region/index.js')
  >['toolbarRegionControlTemplate'];
  tooltip: Awaited<typeof import('./tooltip/index.js')>['tooltipControlTemplate'];
  tree: Awaited<typeof import('./tree/index.js')>['treeControlTemplate'];
  upload: Awaited<typeof import('./upload/index.js')>['uploadControlTemplate'];
};

export type ControlName = keyof ThemeTemplate;
